### ISSUE TITLE
Fieldtrip Open Knowledge Transfer

### ISSUE THREAD

**Issue by benismobile** [edina/Bens-Kanban-Board#1]
breakdown issues need to address so that someone new can use documentation to re-skin and re-purpose fieldtrip open app

**Comment by benismobile** [comment]
actions to assist in knowledge transfer for Fieldtrip open

**Comment by panterz** [comment]
edina/fieldtrip-cobweb-project#122

**Comment by panterz** [comment]
A series of tutorials for developers would be really helpful. I was thinking of:
- [x] A simple tutorial with firing up an app without plugins
- [ ] A way of overwriting the default theme of FTopen and creating your custom app without any plugins in it
- [ ] Start adding plugins on your application
- [ ] Oops, my plugins are outdated, how can I update them?
- [ ] I need to release my apk.
- [ ] cordova update / security patch

**Comment by benismobile** [comment]
Ruben mentioned need to update Cordova (security patch)

**Comment by benismobile** [comment]
can we break this up into 6 issues, where #122 covers item 1 in the list above and update Cordova security is the 6th issue. This is so we can split up the work  of writing the tutorial including George and Ruben.

**Comment by benismobile** [comment]
so sounds like existing documentation will cover most of the questions above. But we still need to create a set of tutorials that point to the relevants bits of documentation. The verify step will assign random people to the questions above and they should be able to follow tutorial and complete tasks without needing to escalate.
