### ISSUE TITLE
Knowledge Transfer IoS iBeacons Tour app

### ISSUE THREAD

**Issue by benismobile** [edina/Bens-Kanban-Board#19]

**Comment by murrayk** [comment]
- [ ] ibeacons floorplan  not compiling for xcode 7.2 and ios 9 - issue with third party library JCTiledScrollView

**Comment by benismobile** [comment]
Do we have enough documentation to enable someone like me to release this.
Can we point to configurable parts of code - i.e. list of beacons, what actions are triggered etc.
