### ISSUE TITLE
UK Borders Knowledge Transfer

### ISSUE THREAD

**Issue by benismobile** [edina/Bens-Kanban-Board#2]

**Comment by panterz** [comment]
- [x] Create an architecture design document. [Link](https://redmine.edina.ac.uk/projects/ukborders/wiki/Architecture)
- [x] Update troubleshooting. [Link](https://redmine.edina.ac.uk/projects/ukborders/wiki/Troubleshooting)
- [x] Update restart guide [Link](https://redmine.edina.ac.uk/projects/ukborders/wiki/Restart_guide)
- [x] Update ukborders_static documentation [Link](https://redmine.edina.ac.uk/projects/ukborders/wiki/Ukborders_static)
- [x] Install UKBorders
- [x] Deploy and Release UKBorders
- [x] Update thematic mapper documentation [Link](https://redmine.edina.ac.uk/projects/ukborders/wiki/Thematic-mapper)
- [x] Update scripts documentation [Link](https://redmine.edina.ac.uk/projects/ukborders/wiki/Extra_scripts)

**Comment by benismobile** [comment]
please provide one or more links next to each tick item above

**Comment by benismobile** [comment]
https://redmine.edina.ac.uk/projects/ukborders/wiki/Authentication
is very brief and does not explain much. Needs to be expanded, Maybe a section on cloning the VM?

**Comment by panterz** [comment]
Check the links above and the doc is updated for Authentication

**Comment by benismobile** [comment]
https://redmine.edina.ac.uk/projects/ukborders/wiki/Databases

"so do all your db related work and test in the (dev) VM at UoE, and do dump/restore to bring data into the VM`s at Essex"

this could do with some fleshing out

**Comment by panterz** [comment]
That's JCrone responsibility/section. Any queries should be addressed to him.
ok that's fine.

**Comment by benismobile** [comment]
https://gitlab.edina.ac.uk/ukborders/ukborders_static/tree/master
please add a README.md

**Comment by benismobile** [comment]
would be good to have a deployment diagram. e.g. live / dev staging etc.

**Comment by panterz** [comment]
Here's the readme one:
https://gitlab.edina.ac.uk/ukborders/ukborders_static/tree/ogr

**Comment by panterz** [comment]
is this not enough?

https://redmine.edina.ac.uk/projects/ukborders/wiki/VMs

**Comment by panterz** [comment]
I've made a diagram. @benismobile you are a collaborator. The reason I am attaching it to the documentation because it needs to be changed soon when UKB becomes live in ESSEX.

**Comment by benismobile** [comment]
the documentation mentions cloning the VM a few times. Do we have anything on what that means? Or do we just ask Matt?
