### ISSUE TITLE
Update the documentation on iOS install/build

### ISSUE THREAD

**Issue by rgamez** [edina/Bens-Kanban-Board#27]
- [x] iOS installation
- [x] iOS customizations
- [x] iOS build
- [x] Known issues

related: https://github.com/edina/fieldtrip-cobweb-project/issues/127

**Comment by rgamez** [comment]
Add [notes](https://github.com/edina/fieldtrip-open/wiki/Install/_compare/7e96022561818c9f0cc7dd3ede81617994d006ea...016ed21771b33e341909b97b30c71c6a8b23a789) about the Xcode 6 requirement

**Comment by rgamez** [comment]
Add [documentation](https://github.com/edina/fieldtrip-open/wiki/Develop/_compare/941ff81d0860601374c1dc3ce99a1d1120c049fb...8531eec2106e8ebf9225c14481e9e56cdf7d010e) for adding icons, splash screens  and the webview padding patch for iOS

**Comment by rgamez** [comment]
Add iOS [build instructions](https://github.com/edina/fieldtrip-open/wiki/Deploy/_compare/d4e50209b5a17ba41b89e2a2057397dd33a6330c...e0a0a2e8aca633302ade8b4edee0b17791f2d93d) and include a reference to the crowdsurvey articles about setting up the App in iTunes Connect

**Comment by rgamez** [comment]
Add issue with the problems encountered with the [upgrade from Cordova 4.x](https://github.com/edina/fieldtrip-cobweb-project/issues/136)

**Comment by colingor** [comment]
Added issue related to iOS build problem here: https://github.com/edina/fieldtrip-open/issues/74
