### ISSUE TITLE
Curious Edinburgh Launch URL

### ISSUE THREAD

**Issue by benismobile** [edina/Bens-Kanban-Board#43]
### [Feature: App should support launching a tour via a URL](https://github.com/edina/Curious-Edinburgh/issues/40)

```
Scenario: Select a launch URL for a tour outside the app 
    Given the app is installed on the device
    And a tour exists in the API
    And a launch URL exists on the device for the user to select
    When the user selects the url on the device
    And the URL protocol is `cityscope://`
    Then the app should be launched
    And the tour details should be downloaded from the API
    And any existing tours should be deleted from the app
    And the tour should be displayed within the app
```
- [x] add launch URL support
- [x] refactor app so that API url isn't hardcoded (use Curious Edinburgh blog by default so as to not break that app)
- [x] handle 404 from launch url

**Comment by ianfieldhouse** [comment]
For now using the protocol `curious-edinburgh://` since the code base hasn't been forked for CityScope as yet.
